### ISSUE TITLE
Dependency check plugin fails after latest NVD updates

### ISSUE THREAD

**Issue by mykolap** [dependency-check/dependency-check-gradle#218]
Version 6.1.5
After fetching data with CVEs - task fails
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at org.owasp.dependencycheck.data.update.NvdCveUpdater.performUpdate(NvdCveUpdater.java:288)
        ... 114 more
Caused by: java.lang.NullPointerException
        at org.owasp.dependencycheck.data.nvd.ecosystem.UrlEcosystemMapper.getEcosystem(UrlEcosystemMapper.java:68)
        at org.owasp.dependencycheck.data.nvd.ecosystem.CveEcosystemMapper.getEcosystem(CveEcosystemMapper.java:74)
        at org.owasp.dependencycheck.data.update.nvd.NvdCveParser.parse(NvdCveParser.java:97)
        at org.owasp.dependencycheck.data.update.nvd.ProcessTask.importJSON(ProcessTask.java:139)
        at org.owasp.dependencycheck.data.update.nvd.ProcessTask.processFiles(ProcessTask.java:152)
        at org.owasp.dependencycheck.data.update.nvd.ProcessTask.call(ProcessTask.java:113)
        at org.owasp.dependencycheck.data.update.nvd.ProcessTask.call(ProcessTask.java:40)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        ... 1 more

it started to fail with another error on 6.1.1
Caused by: org.owasp.dependencycheck.exception.ExceptionCollection: One or more exceptions occurred during analysis:
	UpdateException: org.owasp.dependencycheck.data.nvdcve.DatabaseException: Unable to parse CPE: cpe:2.3:a:archive::tar_project:archive::tar:*:*:*:*:*:perl:*:*
		caused by DatabaseException: Unable to parse CPE: cpe:2.3:a:archive::tar_project:archive::tar:*:*:*:*:*:perl:*:*
		caused by CpeParsingException: Invalid CPE (too many components): cpe:2.3:a:archive::tar_project:archive::tar:*:*:*:*:*:perl:*:*

I tried to upgrade to 6.1.5 - error is different but still not possible to perform analysis

**Comment by harry-jh** [comment]
Also getting this issue this morning on 6.1.4 and 6.1.5

**Comment by TNieminen** [comment]
Experiencing the same issue on 6.1.1.

**Comment by mroeppis** [comment]
Got a similar issue on 6.1.5:
`[org.owasp.dependencycheck.utils.HttpResourceConnection] Error retrieving https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2005.json.gz; received response code 408; Request Time-out`
This first happened one day ago and is still present.

Sadly, `dependencyCheckAggregate` won't run if `dependencyCheckUpdate` fails. I've tried `failOnError=false` but this is probably limited to the `*Analyze` task. Using `autoUpdate=false` works but I don't want to use it as a permanent solution.
I can understand that a missing feed means missing recent data. But can't this be handled by a switch (e.g. `failOnUpdateError`) that allows to continue analysis and maybe just logs the misery at WARN level? In my case all other feeds could be downloaded successfully.

**Comment by jeremylong** [comment]
this was resolved by the NVD.
