### ISSUE TITLE
Plugin is not compatible with h2 2.0.X tested with 6.5.2.1

### ISSUE THREAD

**Issue by gunalmel** [dependency-check/dependency-check-gradle#240]
If h2 ver 2.0.X is in the path (another plugin brings it in the path) then the db initialization SQL statements fail when running dependencyCheck tasks because of reserved keyword use (in the case below that is the column named VALUE). e.g.:

Caused by: org.owasp.dependencycheck.exception.ExceptionCollection: One or more exceptions occurred during analysis:
        DatabaseException: Unable to connect to the dependency-check database
                caused by DatabaseException: Unable to create the database structure
                caused by DatabaseException: Unable to create database statement
                caused by JdbcSQLSyntaxErrorException: Syntax error in SQL statement "\000a\000aCREATE TABLE PROPERTIES (ID VARCHAR(50) PRIMARY KEY, **_VALUE[*]_** VARCHAR(500));\000aINSERT INTO PROPERTIES(ID, VALUE) VALUES ('version', '5.2');"; expected "identifier"; SQL statement:

CREATE TABLE properties (id varchar(50) PRIMARY KEY, value varchar(500));
INSERT INTO properties(id, value) VALUES ('version', '5.2'); [42001-202]
        at org.owasp.dependencycheck.Engine.throwFatalDatabaseException(Engine.java:721)
        at org.owasp.dependencycheck.Engine.initializeAndUpdateDatabase(Engine.java:687)
        at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:606)
        at org.owasp.dependencycheck.Engine$analyzeDependencies$0.call(Unknown Source)
        at org.owasp.dependencycheck.gradle.tasks.AbstractAnalyze.analyze(AbstractAnalyze.groovy:90)
        ... 118 more

**Comment by jeremylong** [comment]
Upgrade for H2 is already planned (and code complete) for the upcoming 7.0 release: https://github.com/jeremylong/DependencyCheck/pull/3928
