### ISSUE TITLE
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "PROPERTIES" not found

### ISSUE THREAD

**Issue by robingood** [dependency-check/dependency-check-gradle#255]
Hello,

I am using the newest version of the plugin for gradle and I am receiving the following error when triggering the dependencyCheckUpdate Task. 

I have also tried with different versions like the 6.2 but the same error occurs.
Inside the C:\Users\\<user>\.gradle\dependency-check-data\5.0 Folder I can see some files being created like odc.mv.db (16Kb), odc.trace.db (1Kb) and a cache folders with files inside (Central, NodeAudit and POM)

./gradlew -v

------------------------------------------------------------
Gradle 6.6.1
------------------------------------------------------------

Build time:   2020-08-25 16:29:12 UTC
Revision:     f2d1fb54a951d8b11d25748e4711bec8d128d7e3

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          1.8.0_312 (Amazon.com Inc. 25.312-b07)
OS:           Windows 10 10.0 amd64

Error

2022-03-17T15:47:11.607+0100 [DEBUG] [org.owasp.dependencycheck.utils.Settings] Settings.getDataFile() - file: 'C:\Users\<user>\.gradle/dependency-check-data/5.0'
2022-03-17T15:47:11.608+0100 [DEBUG] [org.owasp.dependencycheck.utils.Settings] Data directory: C:\Users\<user>\.gradle\dependency-check-data\5.0
2022-03-17T15:47:11.609+0100 [DEBUG] [org.owasp.dependencycheck.utils.Settings] Connection String: 'jdbc:h2:file:C:\Users\<user>\.gradle\dependency-check-data\5.0\odc;AUTOCOMMIT=ON;CACHE_SIZE=65536;RETENTION_TIME=1000;MAX_COMPACT_TI
ME=10000;'
2022-03-17T15:47:11.609+0100 [DEBUG] [org.owasp.dependencycheck.utils.Settings] Settings.getDataFile() - file: 'C:\Users\<user>\.gradle/dependency-check-data/5.0'
2022-03-17T15:47:11.639+0100 [DEBUG] [org.owasp.dependencycheck.utils.WriteLock] Lock file created (Daemon worker Thread 3) 594286f167354acea4067cfee7516998 @ 2022-03-17 15:47:11.64
2022-03-17T15:47:11.640+0100 [DEBUG] [org.owasp.dependencycheck.data.nvdcve.DatabaseManager] Loading driver 'org.h2.Driver'
2022-03-17T15:47:11.640+0100 [DEBUG] [org.owasp.dependencycheck.utils.Settings] Settings.getDataFile() - file: 'C:\Users\<user>\.gradle/dependency-check-data/5.0'
2022-03-17T15:47:11.640+0100 [DEBUG] [org.owasp.dependencycheck.utils.Settings] Data directory: C:\Users\<user>\.gradle\dependency-check-data\5.0
2022-03-17T15:47:11.640+0100 [DEBUG] [org.owasp.dependencycheck.utils.Settings] Connection String: 'jdbc:h2:file:C:\Users\<user>\.gradle\dependency-check-data\5.0\odc;AUTOCOMMIT=ON;CACHE_SIZE=65536;RETENTION_TIME=1000;MAX_COMPACT_TI
ME=10000;'
2022-03-17T15:47:11.640+0100 [DEBUG] [org.owasp.dependencycheck.utils.Settings] Settings.getDataFile() - file: 'C:\Users\<user>\.gradle/dependency-check-data/5.0'
2022-03-17T15:47:11.640+0100 [DEBUG] [org.owasp.dependencycheck.data.nvdcve.DatabaseManager] Need to create DB Structure: false
2022-03-17T15:47:11.641+0100 [DEBUG] [org.owasp.dependencycheck.data.nvdcve.DatabaseManager] Loading database connection
2022-03-17T15:47:11.641+0100 [DEBUG] [org.owasp.dependencycheck.data.nvdcve.DatabaseManager] Connection String: jdbc:h2:file:C:\Users\<user>\.gradle\dependency-check-data\5.0\odc;AUTOCOMMIT=ON;CACHE_SIZE=65536;RETENTION_TIME=1000;MA
X_COMPACT_TIME=10000;
2022-03-17T15:47:11.641+0100 [DEBUG] [org.owasp.dependencycheck.data.nvdcve.DatabaseManager] Database User: dcuser
2022-03-17T15:47:11.653+0100 [DEBUG] [org.owasp.dependencycheck.data.nvdcve.DatabaseManager] Database product: h2
2022-03-17T15:47:11.655+0100 [DEBUG] [org.owasp.dependencycheck.data.nvdcve.DatabaseManager]
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "PROPERTIES" not found; SQL statement:
SELECT value FROM properties WHERE id = 'version' [42102-199]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:451)
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)

**Comment by jeremylong** [comment]
I would suggest running `./gradlew dependencyCheckPurge` - and then trying to run the analyze or aggregate goal.

**Comment by retrofun** [comment]
I had the following similar error with dependency-check-gradle 7.0.3 & gradle 7.4.1 after the update from dependency-check-gradle 6.5.3, ```dependencyCheckAggregate``` task:

```
2022-03-30T10:05:03.913+0200 [DEBUG] [org.owasp.dependencycheck.data.nvdcve.DatabaseManager] Need to create DB Structure: false
2022-03-30T10:05:03.913+0200 [DEBUG] [org.owasp.dependencycheck.data.nvdcve.DatabaseManager] Loading database connection
2022-03-30T10:05:03.913+0200 [DEBUG] [org.owasp.dependencycheck.data.nvdcve.DatabaseManager] Connection String: jdbc:h2:file:/home/<user>/.gradle/dependency-check-data/5.0/odc;AUTOCOMMIT=ON;CACHE_SIZE=65536;RETENTION_TIME=1000;MAX_COMPACT_TIME=10000;
2022-03-30T10:05:03.913+0200 [DEBUG] [org.owasp.dependencycheck.data.nvdcve.DatabaseManager] Database User: dcuser
2022-03-30T10:05:03.997+0200 [DEBUG] [org.owasp.dependencycheck.data.nvdcve.DatabaseManager] Unable to connect to the database
org.h2.jdbc.JdbcSQLNonTransientException: General error: "The write format 1 is smaller than the supported format 2 [2.1.210/5]"
General error: "The write format 1 is smaller than the supported format 2 [2.1.210/5]" [50000-210]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:573)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
	at org.h2.message.DbException.get(DbException.java:216)
	at org.h2.mvstore.db.Store.convertMVStoreException(Store.java:166)
	at org.h2.mvstore.db.Store.<init>(Store.java:140)
	at org.h2.engine.Database.<init>(Database.java:324)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.Driver.connect(Driver.java:59)
```

```./gradlew dependencyCheckPurge``` resolved it. :+1:
