### ISSUE TITLE
V 7.0.0  [org.owasp.dependencycheck.data.nvdcve.DatabaseManager] Unable to connect to the database

### ISSUE THREAD

**Issue by Susapp** [dependency-check/dependency-check-gradle#256]
After updating to 7.0.0 we have problem connection to the database when running on our jenkins agent.
Locally this works fine, but I can't understand why this would be a problem.
The stacktrace seems to be originating from:
[Update.groovy](https://github.com/dependency-check/dependency-check-gradle/blob/d02f8d505b5046995e887d8a1a00ec5f4fb2aa9e/src/main/groovy/org/owasp/dependencycheck/gradle/tasks/Update.groovy#L54)

Did some digging on the error "The write format 1 is smaller than the supported format 2 [2.1.210/5]" and it seems to be related to a vulnerability fix for H2 https://www.minisoft.com/support/index.php/jndi-vulnerability-in-h2-database-consoles/ . As we do not specify H2 version or configure it my guess is that it is defined in 7.0.0.

Any thoughts?

The stack trace is:
`2022-03-18T07:43:17.499+0000 [DEBUG] [org.owasp.dependencycheck.data.nvdcve.DatabaseManager] Database User: dcuser
2022-03-18T07:43:17.787+0000 [DEBUG] [org.owasp.dependencycheck.data.nvdcve.DatabaseManager] Unable to connect to the database
org.h2.jdbc.JdbcSQLNonTransientException: General error: "The write format 1 is smaller than the supported format 2 [2.1.210/5]" [50000-210]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:573)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
	at org.h2.message.DbException.get(DbException.java:216)
	at org.h2.mvstore.db.Store.convertMVStoreException(Store.java:166)
	at org.h2.mvstore.db.Store.<init>(Store.java:140)
	at org.h2.engine.Database.<init>(Database.java:324)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.Driver.connect(Driver.java:59)
	at platform/java.sql@15/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at platform/java.sql@15/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at org.owasp.dependencycheck.data.nvdcve.DatabaseManager.initialize(DatabaseManager.java:185)
	at org.owasp.dependencycheck.data.nvdcve.DatabaseManager.<init>(DatabaseManager.java:123)
	at org.owasp.dependencycheck.data.nvdcve.CveDB.<init>(CveDB.java:242)
	at org.owasp.dependencycheck.Engine.openDatabase(Engine.java:995)
	at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:868)
	at org.owasp.dependencycheck.Engine.initializeAndUpdateDatabase(Engine.java:683)
	at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:609)
	at org.owasp.dependencycheck.Engine$analyzeDependencies$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:130)
	at org.owasp.dependencycheck.gradle.tasks.AbstractAnalyze.analyze(AbstractAnalyze.groovy:90)
	at java.base@15/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@15/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base@15/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@15/java.lang.reflect.Method.invoke(Method.java:564)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:58)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:51)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:29)
	at org.gradle.api.internal.tasks.execution.TaskExecution$3.run(TaskExecution.java:242)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:68)
	at org.gradle.api.internal.tasks.execution.TaskExecution.executeAction(TaskExecution.java:227)
	at org.gradle.api.internal.tasks.execution.TaskExecution.executeActions(TaskExecution.java:210)
	at org.gradle.api.internal.tasks.execution.TaskExecution.executeWithPreviousOutputFiles(TaskExecution.java:193)
	at org.gradle.api.internal.tasks.execution.TaskExecution.execute(TaskExecution.java:171)
	at org.gradle.internal.execution.steps.ExecuteStep.executeInternal(ExecuteStep.java:89)
	at org.gradle.internal.execution.steps.ExecuteStep.access$000(ExecuteStep.java:40)
	at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:53)
	at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:50)
Caused by: org.h2.mvstore.MVStoreException: The write format 1 is smaller than the supported format 2 [2.1.210/5]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004)
	at org.h2.mvstore.MVStore.getUnsupportedWriteFormatException(MVStore.java:1059)
	at org.h2.mvstore.MVStore.readStoreHeader(MVStore.java:878)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:455)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:4056)
	at org.h2.mvstore.db.Store.<init>(Store.java:129)
	... 145 more`

**Comment by jeremylong** [comment]
Did you read the release notes? 

https://github.com/jeremylong/DependencyCheck/releases/tag/v7.0.0
https://github.com/jeremylong/DependencyCheck#700-upgrade-notice

You need to purge the database.

**Comment by Susapp** [comment]
Thanks, I had missed that totally.
