### ISSUE TITLE
7.0.1: Could not find matching constructor for: java.io.File(File) when dealing with virtual dependencies

### ISSUE THREAD

**Issue by chadlwilson** [dependency-check/dependency-check-gradle#258]
With `7.0.1` virtual dependencies also do not seem to work properly.

```
Caused by: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: java.io.File(File)
        at org.owasp.dependencycheck.gradle.tasks.AbstractAnalyze.addDependency(AbstractAnalyze.groovy:509)
        at org.owasp.dependencycheck.gradle.tasks.AbstractAnalyze.addDependency(AbstractAnalyze.groovy)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.owasp.dependencycheck.gradle.tasks.AbstractAnalyze$_processConfigV4_closure14$_closure18.doCall(AbstractAnalyze.groovy:457)
        at jdk.internal.reflect.GeneratedMethodAccessor37.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.owasp.dependencycheck.gradle.tasks.AbstractAnalyze$_processConfigV4_closure14.doCall(AbstractAnalyze.groovy:437)
```

Problematic code is at https://github.com/dependency-check/dependency-check-gradle/blob/c485d5ec01856672c0cb559e5b4496fa9af2af51/src/main/groovy/org/owasp/dependencycheck/gradle/tasks/AbstractAnalyze.groovy#L507-L510

Seems to be caused by https://github.com/dependency-check/dependency-check-gradle/pull/252

`project.buildFile` is already a `File` object in the Gradle API (not a `String`), and as there is no such copy-constructor signature in `java.io.File` this fails. Probably the `new File(..)` is not needed around `project.buildFile`?

Seems to at its root have the same missing tests as allowed https://github.com/dependency-check/dependency-check-gradle/issues/247 to get through?

**Comment by steurt** [comment]
Same issue here.
