### ISSUE TITLE
7.0.2: Could not get unknown property 'd' for task :dependencyCheckAggregate 

### ISSUE THREAD

**Issue by chadlwilson** [dependency-check/dependency-check-gradle#263]
`7.0.2` seems to have another problem (after you have got past #260)?:

```
Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'd' for task ':dependencyCheckAggregate' of type org.owasp.dependencycheck.gradle.tasks.Aggregate.
        at org.gradle.internal.metaobject.AbstractDynamicObject.getMissingProperty(AbstractDynamicObject.java:85)
        at org.gradle.internal.metaobject.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:62)
        at org.owasp.dependencycheck.gradle.tasks.Aggregate_Decorated.getProperty(Unknown Source)
        at org.owasp.dependencycheck.gradle.tasks.AbstractAnalyze.addDependency(AbstractAnalyze.groovy:529)
        at org.owasp.dependencycheck.gradle.tasks.AbstractAnalyze.addDependency(AbstractAnalyze.groovy)
```

There is no variable/property `d` it seems - looks like another typo, and it should be `dependency.addAsEvidence`?

https://github.com/dependency-check/dependency-check-gradle/blob/0ada84adbd3f867ac329a6ce71d646b16e6b7c9a/src/main/groovy/org/owasp/dependencycheck/gradle/tasks/AbstractAnalyze.groovy#L529-L530

**Comment by jeremylong** [comment]
Thanks - sorry about this...  I'm going to re-work some of the testing to ensure things like this are covered in the future.
