### ISSUE TITLE
Got error while task execution

### ISSUE THREAD

**Issue by glcanvas** [dependency-check/dependency-check-gradle#271]
hello!
got this error

`
2022-07-05T18:47:51.079+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
Execution failed for task ':services:index-publisher:dependencyCheckUpdate'.
> No such property: autoUpdate for class: java.lang.String
`

do you have any idea what happened here? And how I can resolve it?

**Comment by glcanvas** [comment]
a bit more stack trace
`
Caused by: groovy.lang.MissingPropertyException: No such property: autoUpdate for class: java.lang.String
	at org.owasp.dependencycheck.gradle.tasks.ConfiguredTask.initializeSettings(ConfiguredTask.groovy:70)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
`
