### ISSUE TITLE
Regression on proxy handling

### ISSUE THREAD

**Issue by moley** [dependency-check/dependency-check-gradle#295]
Hello everyone, 

We are facing a problem, when running the task dependencyCheckAggregate behind out proxy:
`
Caused by: org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'xxxx' with class 'java.lang.String' to class 'java.lang.Integer'
        at org.owasp.dependencycheck.gradle.extension.ProxyExtension.setProperty(ProxyExtension.groovy)
        at org.owasp.dependencycheck.gradle.tasks.ConfiguredTask.configureProxy(ConfiguredTask.groovy:196)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
`

The problem seems to be you have eliminated usage of internal gradle api with https://github.com/dependency-check/dependency-check-gradle/commit/2001e1467af0066349177c47d68779c918ae47d9 
but did not take in account the port, which was in the gradle objects before an integer is now with environment variable handling a string. Workaround for me currently is backporting to version 7.3.0, which was working, waiting for this issue to be fixed. Thanks a lot

**Comment by herrlock** [comment]
This was fixed, but did not make it into the 7.4.0 (I assume by mistake)
https://github.com/jeremylong/DependencyCheck/issues/5076#issuecomment-1337474449

**Comment by jeremylong** [comment]
Yeah - sorry about that. i really need to automate the release process for the gradle plugin so mistakes like this don't happen...
