### ISSUE TITLE
Trying to register JCSAdminBean twice. Could not register JMX bean. javax.management.InstanceAlreadyExistsException

### ISSUE THREAD

**Issue by khshanovskyi** [dependency-check/dependency-check-gradle#309]
Using gradle 6.9.3 with dependencycheck 8.0.0 the following exception is printed when running dependencyCheckAnalyze:
Previously this issue was closed with no changes https://github.com/dependency-check/dependency-check-gradle/issues/217
Before I was using 7.4.4 and this exception didn't affect the build but on 8.0.0 a build fails

```
 > Task :dependencyCheckAnalyze
Could not register JMX bean.
javax.management.InstanceAlreadyExistsException: org.apache.commons.jcs:type=JCSAdminBean
        at java.management/com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:436)
        at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(DefaultMBeanServerInterceptor.java:1855)
        at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:955)
        at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:890)
        at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:320)
        at java.management/com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
        at org.apache.commons.jcs.engine.control.CompositeCacheManager.initialize(CompositeCacheManager.java:271)
        at org.apache.commons.jcs.engine.control.CompositeCacheManager.getUnconfiguredInstance(CompositeCacheManager.java:218)
        at org.apache.commons.jcs.JCS.getCacheManager(JCS.java:162)
        at org.apache.commons.jcs.JCS.getInstance(JCS.java:205)
        at org.owasp.dependencycheck.data.cache.DataCacheFactory.getPomCache(DataCacheFactory.java:155)
```

**Comment by khshanovskyi** [comment]
with version 8.0.1 this bug is disappear
thank you
