### ISSUE TITLE
publishedSuppressions.xml availability causes stacktrace

### ISSUE THREAD

**Issue by quotidian-ennui** [dependency-check/dependency-check-gradle#333]
Basically there's always a stack trace with dependency-check-gradle 8.1.2+

It doesn't stop `dependencyCheckAnalyze` from working, but it is distracting, since it could make you think there's a problem when there really isn't.

```
Verifying dependencies for project gitlab-terraform
Checking for updates and analyzing dependencies for vulnerabilities
Failed to update hosted suppressions file, results may contain false positives already resolved by the DependencyCheck project
org.owasp.dependencycheck.data.update.exception.UpdateException: Failed to update the hosted suppressions file
        at org.owasp.dependencycheck.data.update.HostedSuppressionsDataSource.fetchHostedSuppressions(HostedSuppressionsDataSource.java:136)
... // skipped for brevity
Caused by: org.owasp.dependencycheck.utils.DownloadFailedException: Error downloading file https://jeremylong.github.io/DependencyCheck/suppressions/publishedSuppressions.xml; unable to connect.
        at org.owasp.dependencycheck.utils.HttpResourceConnection.obtainConnection(HttpResourceConnection.java:267)
        at org.owasp.dependencycheck.utils.HttpResourceConnection.fetch(HttpResourceConnection.java:163)
        at org.owasp.dependencycheck.utils.Downloader.fetchFile(Downloader.java:130)
        ... 128 more
Caused by: javax.net.ssl.SSLException: Unsupported or unrecognized SSL message
```

## Additional Info

- This manifests itself as a `SSL_ERROR_RX_RECORD_TOO_LONG` in Firefox. 
- curl gives us this
```
$ curl -vvv  https://jeremylong.github.io/DependencyCheck/suppressions/publishedSuppressions.xml
*   Trying 185.199.108.153:443...
* Connected to jeremylong.github.io (185.199.108.153) port 443 (#0)
* ALPN: offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* OpenSSL/3.0.8: error:0A00010B:SSL routines::wrong version number
* Closing connection 0
curl: (35) OpenSSL/3.0.8: error:0A00010B:SSL routines::wrong version number
```

## Minimal Gradle configuration

- It's a Quarkus project with owasp dependency check layered over the top.

```
plugins {
  id 'org.owasp.dependencycheck' version '8.1.2'
}
dependencyCheck  {
  suppressionFiles= [ "https://raw.githubusercontent.com/telus-agcg/interlok-build-parent/develop/owasp-exclude.xml", "$rootDir/gradle/owasp-exclude.xml"]
  scanConfigurations = [ "api", "compileClasspath", "runtimeClasspath" ]
  formats = [ "HTML", "JUNIT" ]
  junitFailOnCVSS = 7.0
  failBuildOnCVSS = 7.0
  analyzers {
    assemblyEnabled=false
  }
}
```

## Resolution

- reconfigure jeremylong.github.io TLS/SSL if you're able to, so it doesn't cause this error. This seems like it's the best thing.
- (Eat the error since it's a non-fatal error).

**Comment by jeremylong** [comment]
Was this a temporary error? I'm not seeing the wrong version number when I use curl...  I don't really control the TLS configuration on the gh-pages....

**Comment by quotidian-ennui** [comment]
I realised that it was probably gh-pages because of the .github.io, I just checked it again (previous failure was on this laptop as well) on my corporate laptop. It had been consistently failing on this laptop (over the last week or so), but because of other reasons, I had no other machines to test it on...

```
$ curl -vvv  https://jeremylong.github.io/DependencyCheck/suppressions/publishedSuppressions.xml
*   Trying 185.199.111.153:443...
* Connected to jeremylong.github.io (185.199.111.153) port 443 (#0)
* ALPN: offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: ...\curl-ca-bundle.crt
*  CApath: none
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN: server accepted h2
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=GitHub, Inc.; CN=*.github.io
*  start date: Feb 21 00:00:00 2023 GMT
*  expire date: Mar 20 23:59:59 2024 GMT
*  subjectAltName: host "jeremylong.github.io" matched cert's "*.github.io"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert TLS RSA SHA256 2020 CA1
*  SSL certificate verify ok.
* using HTTP/2
* h2h3 [:method: GET]
* h2h3 [:path: /DependencyCheck/suppressions/publishedSuppressions.xml]
* h2h3 [:scheme: https]
* h2h3 [:authority: jeremylong.github.io]
* h2h3 [user-agent: curl/8.0.1]
* h2h3 [accept: */*]
* Using Stream ID: 1 (easy handle 0x19bc9a50240)
> GET /DependencyCheck/suppressions/publishedSuppressions.xml HTTP/2
> Host: jeremylong.github.io
> user-agent: curl/8.0.1
> accept: */*
```

It's now working, we can probably just chalk it up to "corporate AV/firewall/endpoint shenanigans"

It still raises an interesting point about this being a non-fatal exception which might confuse users, so from a developer-experience point of view it might still be worth logging the exception at verbose/debug only?

I have no problem if you close the issue though.

**Comment by jeremylong** [comment]
I think we'll leave the reporting as is - it alerts people that they may need to configure the corporate proxy.
